src/main/java/seedu/weme/logic/commands/MemeEditCommand.java, src/main/java/seedu/weme/logic/parser/MemeEditCommandParser.java, src/test/java/seedu/weme/logic/parser/MemeEditCommandParserTest.java, src/test/java/seedu/weme/logic/parser/MemeParserTest.java, src/test/java/seedu/weme/testutil/MemeUtil.java
Remove file path field for EditCommand for user and fix relevant tests.
=> Remove filepath from EditCommand

src/main/java/seedu/weme/logic/Logic.java, src/main/java/seedu/weme/logic/LogicManager.java, src/main/java/seedu/weme/model/Model.java, src/main/java/seedu/weme/model/ModelManager.java, src/main/java/seedu/weme/ui/MainWindow.java, src/test/java/seedu/weme/logic/commands/MemeAddCommandTest.java
Closes #62 as delete no longer needs to touch files.
=> Add file cleanup on exit

src/main/java/seedu/weme/logic/commands/MemeClearCommand.java, src/main/java/seedu/weme/model/Model.java, src/main/java/seedu/weme/model/ModelManager.java, src/test/java/seedu/weme/logic/commands/MemeAddCommandTest.java, src/test/java/seedu/weme/logic/commands/MemeClearCommandTest.java
MemeClearCommand was clearing the whole Weme. Changed to only clear
Memes
=> Fix MemeClearCommand

src/main/java/seedu/weme/logic/commands/MemeLikeCommand.java, src/main/java/seedu/weme/model/Model.java, src/main/java/seedu/weme/model/ModelManager.java, src/main/java/seedu/weme/model/Weme.java, src/main/java/seedu/weme/statistics/LikeData.java, src/main/java/seedu/weme/statistics/LikeManager.java, src/main/java/seedu/weme/statistics/Stats.java, src/main/java/seedu/weme/statistics/StatsManager.java, src/main/java/seedu/weme/storage/JsonSerializableStats.java, src/test/java/seedu/weme/logic/commands/MemeAddCommandTest.java
=> Fix Undo for LikeCommand

src/main/java/seedu/weme/commons/core/Messages.java, src/main/java/seedu/weme/logic/commands/TemplateAddCommand.java, src/main/java/seedu/weme/logic/commands/TemplateDeleteCommand.java, src/main/java/seedu/weme/logic/commands/TemplateEditCommand.java, src/main/java/seedu/weme/logic/parser/ArgumentMultimap.java, src/main/java/seedu/weme/logic/parser/MemeAddCommandParser.java, src/main/java/seedu/weme/logic/parser/ParserUtil.java, src/main/java/seedu/weme/logic/parser/TemplateAddCommandParser.java, src/main/java/seedu/weme/logic/parser/TemplateDeleteCommandParser.java, src/main/java/seedu/weme/logic/parser/TemplateEditCommandParser.java, src/main/java/seedu/weme/logic/parser/TemplateParser.java, src/main/java/seedu/weme/model/Model.java, src/main/java/seedu/weme/model/ModelManager.java, src/test/java/seedu/weme/logic/commands/MemeAddCommandTest.java
- Add `TemplateAddCommand`
- Add `TemplateEditCommand`
- Add `TemplateDeleteCommand`
- Add the corresponding parsers
- TODO tests will be added in another PR
Closes #11
=> Add template commands

src/main/java/seedu/weme/logic/commands/createcommand/CreateCommand.java, src/main/java/seedu/weme/logic/parser/commandparser/createcommandparser/CreateCommandParser.java, src/main/java/seedu/weme/logic/parser/contextparser/CreateParser.java, src/main/java/seedu/weme/model/template/MemeCreation.java, src/main/java/seedu/weme/model/util/ImageUtil.java
New memes can now be created from templates
Closes #13
=> Implement CreateCommand for meme creation

src/main/java/seedu/weme/commons/util/FileUtil.java, src/main/java/seedu/weme/logic/commands/exportcommand/ExportCommand.java, src/main/java/seedu/weme/logic/parser/commandparser/exportcommandparser/ExportCommandParser.java, src/main/java/seedu/weme/logic/parser/util/ParserUtil.java, src/main/java/seedu/weme/model/DirectoryPath.java, src/main/java/seedu/weme/model/Model.java, src/main/java/seedu/weme/model/ModelManager.java, src/main/java/seedu/weme/model/UserPrefs.java, src/main/java/seedu/weme/storage/JsonWemeStorage.java, src/test/java/seedu/weme/logic/commands/memecommand/MemeAddCommandTest.java
Issue #129: Enables the user to export memes to a default path by using p/d for the path prefix in the ExportCommand
=> Add Default Export Path to ExportCommand

src/main/java/seedu/weme/logic/commands/createcommand/TextAddCommand.java, src/main/java/seedu/weme/logic/commands/memecommand/MemeAddCommand.java, src/main/java/seedu/weme/logic/commands/memecommand/MemeEditCommand.java, src/main/java/seedu/weme/logic/commands/templatecommand/TemplateAddCommand.java, src/main/java/seedu/weme/logic/commands/templatecommand/TemplateEditCommand.java, src/main/java/seedu/weme/logic/prompter/commandprompter/createcommandprompter/TextAddCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/exportcommandpropmter/ExportCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/templatecommandprompter/TemplateUseCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/contextprompter/CreatePrompter.java, src/main/java/seedu/weme/logic/prompter/contextprompter/TemplatePrompter.java, src/main/java/seedu/weme/logic/prompter/util/PrompterUtil.java, src/main/java/seedu/weme/model/Model.java, src/main/java/seedu/weme/model/ModelManager.java, src/main/java/seedu/weme/model/Records.java, src/main/java/seedu/weme/model/RecordsManager.java, src/main/java/seedu/weme/model/Weme.java, src/main/java/seedu/weme/model/util/SampleDataUtil.java, src/main/java/seedu/weme/storage/JsonSerializableRecords.java, src/test/data/JsonSerializableWemeTest/typicalWeme.json, src/test/java/seedu/weme/logic/commands/memecommand/MemeAddCommandTest.java
Add command prompt for `ExportCommand` and `TextAddCommand`.
Closes #145
=> Add more command prompt

src/main/java/seedu/weme/logic/commands/exportcommand/ExportClearCommand.java, src/main/java/seedu/weme/logic/commands/importcommand/ImportClearCommand.java, src/main/java/seedu/weme/logic/commands/importcommand/ImportCommand.java, src/main/java/seedu/weme/logic/commands/importcommand/ImportDeleteCommand.java, src/main/java/seedu/weme/logic/commands/importcommand/ImportEditCommand.java, src/main/java/seedu/weme/logic/parser/commandparser/importcommandparser/ImportDeleteCommandParser.java, src/main/java/seedu/weme/logic/parser/commandparser/importcommandparser/ImportEditCommandParser.java, src/main/java/seedu/weme/logic/parser/contextparser/ExportParser.java, src/main/java/seedu/weme/logic/parser/contextparser/ImportParser.java, src/main/java/seedu/weme/model/Model.java, src/main/java/seedu/weme/model/ModelManager.java, src/main/java/seedu/weme/model/Weme.java, src/test/java/seedu/weme/logic/commands/memecommand/MemeAddCommandTest.java, src/test/java/seedu/weme/logic/parser/commandparser/importcommandparser/ImportDeleteCommandParserTest.java, src/test/java/seedu/weme/logic/parser/commandparser/importcommandparser/ImportEditCommandParserTest.java
I am planning to extract out the internal EditMemeDescriptor class in MemeEditCommand since ImportEditCommand also needs it.
=> Add Support Commands for Import and Export

src/main/java/seedu/weme/logic/commands/importcommand/ImportEditCommand.java
=> Fix compilation bug

src/main/java/seedu/weme/commons/core/Messages.java, src/main/java/seedu/weme/logic/commands/createcommand/TextAddCommand.java, src/main/java/seedu/weme/logic/commands/createcommand/TextDeleteCommand.java, src/main/java/seedu/weme/logic/commands/createcommand/TextEditCommand.java, src/main/java/seedu/weme/logic/parser/commandparser/createcommandparser/TextDeleteCommandParser.java, src/main/java/seedu/weme/logic/parser/commandparser/createcommandparser/TextEditCommandParser.java, src/main/java/seedu/weme/logic/parser/contextparser/CreateParser.java, src/main/java/seedu/weme/logic/parser/util/CliSyntax.java, src/main/java/seedu/weme/logic/parser/util/ParserUtil.java, src/main/java/seedu/weme/model/template/Coordinates.java, src/main/java/seedu/weme/model/template/MemeCreation.java, src/main/java/seedu/weme/model/template/MemeText.java, src/main/java/seedu/weme/model/template/MemeTextColor.java, src/main/java/seedu/weme/model/template/exceptions/MemeTextNotFoundException.java, src/main/java/seedu/weme/model/template/exceptions/TemplateNotFoundException.java, src/main/java/seedu/weme/ui/CreateImageDisplay.java, src/main/java/seedu/weme/ui/MemeTextCard.java, src/main/java/seedu/weme/ui/MemeTextListPanel.java, src/main/resources/view/CreateImageDisplay.fxml, src/main/resources/view/DarkTheme.css, src/main/resources/view/MemeGridCard.fxml, src/main/resources/view/MemeTextCard.fxml, src/main/resources/view/MemeTextListPanel.fxml
=> Support editing and deleting text in meme creation

src/main/java/seedu/weme/ui/CommandBox.java, src/main/java/seedu/weme/ui/MainWindow.java
I have no choice but to pass in the ObservableList. Anyone has a better suggestion? Or does anyone think this is not needed for Mock PE?
=> Add upper bound for index toggling

src/main/java/seedu/weme/model/Weme.java
closes #214 
Add default dislike data for new meme.
=> Fix bug caused by dislike

src/main/java/seedu/weme/logic/commands/createcommand/TextDeleteCommand.java, src/main/java/seedu/weme/logic/commands/createcommand/TextEditCommand.java, src/main/java/seedu/weme/logic/prompter/commandprompter/createcommandprompter/TextAddCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/createcommandprompter/TextDeleteCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/createcommandprompter/TextEditCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/exportcommandpropmter/ExportCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/importcommandprompter/ImportEditCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/importcommandprompter/LoadCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/memecommandprompter/MemeAddCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/memecommandprompter/MemeEditCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/memecommandprompter/MemeFindCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/templatecommandprompter/TemplateAddCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/templatecommandprompter/TemplateEditCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/contextprompter/CreatePrompter.java, src/main/java/seedu/weme/logic/prompter/util/PrompterUtil.java, src/main/java/seedu/weme/model/Model.java, src/main/java/seedu/weme/model/ModelManager.java, src/main/java/seedu/weme/model/Records.java, src/main/java/seedu/weme/model/RecordsManager.java, src/main/java/seedu/weme/model/Weme.java, src/main/java/seedu/weme/model/util/SampleDataUtil.java, src/main/java/seedu/weme/storage/JsonSerializableRecords.java, src/test/data/JsonSerializableWemeTest/typicalWeme.json, src/test/java/seedu/weme/logic/commands/memecommand/MemeAddCommandTest.java
- Add command prompt for `TextEditCommand` and  `TextDeleteCommand`.
- Refactor util method in `PrompterUtil` to suit different contexts.
=> Finish command prompt for all commands

docs/UserGuide.adoc, src/main/java/seedu/weme/commons/core/Messages.java, src/main/java/seedu/weme/logic/commands/memecommand/MemeFindCommand.java, src/main/java/seedu/weme/logic/commands/templatecommand/TemplateClearCommand.java, src/main/java/seedu/weme/logic/commands/templatecommand/TemplateFindCommand.java, src/main/java/seedu/weme/logic/commands/templatecommand/TemplateListCommand.java, src/main/java/seedu/weme/logic/parser/commandparser/templatecommandparser/TemplateFindCommandParser.java, src/main/java/seedu/weme/logic/parser/contextparser/TemplateParser.java, src/main/java/seedu/weme/model/Model.java, src/main/java/seedu/weme/model/ModelManager.java, src/main/java/seedu/weme/model/meme/TagContainsKeywordsPredicate.java, src/main/java/seedu/weme/model/template/NameContainsKeywordsPredicate.java, src/test/java/seedu/weme/logic/commands/memecommand/MemeAddCommandTest.java, src/test/java/seedu/weme/logic/commands/memecommand/MemeFindCommandTest.java
=> Add list, find, and clear commands for templates

docs/UserGuide.adoc, src/main/java/seedu/weme/logic/commands/createcommand/TextEditCommand.java, src/main/java/seedu/weme/logic/commands/createcommand/TextMoveCommand.java, src/main/java/seedu/weme/logic/parser/commandparser/createcommandparser/TextMoveCommandParser.java, src/main/java/seedu/weme/logic/parser/contextparser/CreateParser.java, src/main/java/seedu/weme/logic/parser/util/ParserUtil.java, src/main/java/seedu/weme/model/template/Coordinates.java, src/main/java/seedu/weme/model/template/MemeTextColor.java, src/main/java/seedu/weme/model/template/MemeTextSize.java, src/main/java/seedu/weme/model/template/MemeTextStyle.java, src/main/java/seedu/weme/model/template/exceptions/InvalidCoordinatesException.java, src/main/java/seedu/weme/ui/CommandBox.java, src/main/java/seedu/weme/ui/MainWindow.java
Closes #205 
Also closes #229 due to refactoring key press listeners of the command box.
=> Support moving text with arrow keys

docs/UserGuide.adoc
=> Make the User Guide more explicit to prevent some of the issues reported in PED

src/main/java/seedu/weme/logic/Logic.java, src/main/java/seedu/weme/logic/LogicManager.java, src/main/java/seedu/weme/logic/commands/memecommand/MemeViewCommand.java, src/main/java/seedu/weme/logic/parser/commandparser/memecommandparser/MemeViewCommandParser.java, src/main/java/seedu/weme/logic/parser/contextparser/MemeParser.java, src/main/java/seedu/weme/logic/parser/util/ParserUtil.java, src/main/java/seedu/weme/model/Model.java, src/main/java/seedu/weme/model/ModelContext.java, src/main/java/seedu/weme/model/ModelManager.java, src/main/java/seedu/weme/model/ReadOnlyWeme.java, src/main/java/seedu/weme/model/Weme.java, src/main/java/seedu/weme/ui/MainWindow.java, src/main/java/seedu/weme/ui/TabBar.java, src/main/java/seedu/weme/ui/ViewPanel.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/ViewPanel.fxml, src/test/java/seedu/weme/logic/commands/memecommand/MemeAddCommandTest.java, src/test/java/seedu/weme/logic/commands/memecommand/MemeViewCommandTest.java, src/test/java/seedu/weme/logic/parser/commandparser/memecommandparser/MemeViewCommandParserTest.java, src/test/java/seedu/weme/model/WemeTest.java
Add ViewPanel
Fix ViewPanel
Add View Command Implementation
=> Add MemeViewCommand

src/main/java/seedu/weme/logic/parser/contextparser/ViewParser.java, src/main/java/seedu/weme/logic/parser/util/ParserUtil.java, src/main/java/seedu/weme/logic/prompter/contextprompter/ViewPrompter.java, src/main/java/seedu/weme/logic/prompter/util/PrompterUtil.java, src/test/java/seedu/weme/logic/parser/commandparser/memecommandparser/MemeViewCommandParserTest.java
hack :(
Override undo redo in sub parser and prompter to restore default behaviour as if undo redo does not exist.
=> Remove UndoRedo from view context

src/main/java/seedu/weme/logic/prompter/commandprompter/createcommandprompter/TextMoveCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/memecommandprompter/MemeViewCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/templatecommandprompter/TemplateFindCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/contextprompter/CreatePrompter.java, src/main/java/seedu/weme/logic/prompter/contextprompter/MemePrompter.java, src/main/java/seedu/weme/logic/prompter/contextprompter/TemplatePrompter.java, src/main/java/seedu/weme/logic/prompter/util/PrompterUtil.java, src/main/java/seedu/weme/ui/CommandBox.java
Add prompters for:
-`TemplateFindCommand`
-`TemplateListCommand`
-`TemplateClearCommand`
-`TextMoveCommand`
-`MemeViewCommand`
=> Add more prompters

docs/DeveloperGuide.adoc, docs/UserGuide.adoc, src/main/java/seedu/weme/commons/core/GuiSettings.java, src/main/java/seedu/weme/ui/CreatePanel.java, src/main/java/seedu/weme/ui/MainWindow.java, src/main/java/seedu/weme/ui/ViewPanel.java, src/main/resources/view/MainWindow.fxml, src/main/resources/view/TabBar.fxml, src/main/resources/view/ViewPanel.fxml
=> Fix UI window sizing

src/main/java/seedu/weme/commons/util/FileUtil.java, src/main/java/seedu/weme/model/path/ImagePath.java, src/test/java/seedu/weme/commons/util/FileUtilTest.java, src/test/java/seedu/weme/logic/commands/exportcommand/ExportCommandTest.java, src/test/java/seedu/weme/logic/commands/memecommand/MemeViewCommandTest.java
=> Add more tests

docs/DeveloperGuide.adoc, src/main/java/seedu/weme/logic/prompter/commandprompter/createcommandprompter/TextEditCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/importcommandprompter/ImportEditCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/memecommandprompter/MemeEditCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/memecommandprompter/MemeFindCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/templatecommandprompter/TemplateEditCommandPrompter.java, src/main/java/seedu/weme/logic/prompter/commandprompter/templatecommandprompter/TemplateFindCommandPrompter.java
- Add manual testing instructions for command suggestion and auto-completion feature.
- Fix minor bugs in  edit and find command prompters.
=> Add manual testing for command suggestions
